### ISSUE TITLE
Compile and install errors in the latest version of phd2

### ISSUE THREAD

**Issue by sn3ik** [OpenPHDGuiding/phd2#1092]
Hi, I have been using PHD2 for several years on various operating systems without ever having had any problems. For convenience I use a Debian based raspberry4, so I have to compile PHD2 using the classic procedure.
But in recent days when I run cmake I get many errors,
initially it was looking for the indi-2.0.3.tar.gz archive in /thirdparty causing lots of errors, after placing it manually, it can't find many of the .h libraries in the established paths, I tried to change the paths manually but it's a big job .

Has anyone had the same problem?

I attach the log

fra@AstroPI:~/phd2/tmp $ cmake -DOPENSOURCE_ONLY=1 ..
-- PHD2 version '2.6.11' (extracted from source)
-- using libcurl /usr/lib/aarch64-linux-gnu/libcurl.so
-- Using project provided libindi '/home/fra/phd2/thirdparty/indi-2.0.3.tar.gz'
-- [thirdparty] extracting libindi sources
-- Found libnova: /usr/lib/aarch64-linux-gnu/libnova.so
CMake Error: File /home/fra/phd2/tmp/external_libs_deflate/indi-2.0.3/libs/indibase/baseclient.h does not exist.
CMake Error at thirdparty/thirdparty.cmake:758 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:125 (include)

CMake Error: File /home/fra/phd2/tmp/external_libs_deflate/indi-2.0.3/indiapi.h does not exist.
CMake Error at thirdparty/thirdparty.cmake:801 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:125 (include)

CMake Error: File /home/fra/phd2/tmp/external_libs_deflate/indi-2.0.3/indidevapi.h does not exist.
CMake Error at thirdparty/thirdparty.cmake:801 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:125 (include)

CMake Error: File /home/fra/phd2/tmp/external_libs_deflate/indi-2.0.3/base64.h does not exist.
CMake Error at thirdparty/thirdparty.cmake:801 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:125 (include)

CMake Error: File /home/fra/phd2/tmp/external_libs_deflate/indi-2.0.3/libs/lilxml.h does not exist.
CMake Error at thirdparty/thirdparty.cmake:801 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:125 (include)

CMake Error: File /home/fra/phd2/tmp/external_libs_deflate/indi-2.0.3/libs/indicom.h does not exist.
CMake Error at thirdparty/thirdparty.cmake:801 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:125 (include)

CMake Error: File /home/fra/phd2/tmp/external_libs_deflate/indi-2.0.3/eventloop.h does not exist.
CMake Error at thirdparty/thirdparty.cmake:801 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:125 (include)

CMake Error: File /home/fra/phd2/tmp/external_libs_deflate/indi-2.0.3/indidriver.h does not exist.
CMake Error at thirdparty/thirdparty.cmake:801 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:125 (include)

CMake Error: File /home/fra/phd2/tmp/external_libs_deflate/indi-2.0.3/libs/indibase/indibase.h does not exist.
CMake Error at thirdparty/thirdparty.cmake:801 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:125 (include)

CMake Error: File /home/fra/phd2/tmp/external_libs_deflate/indi-2.0.3/libs/indibase/indibasetypes.h does not exist.
CMake Error at thirdparty/thirdparty.cmake:801 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:125 (include)

CMake Error: File /home/fra/phd2/tmp/external_libs_deflate/indi-2.0.3/libs/indibase/basedevice.h does not exist.
CMake Error at thirdparty/thirdparty.cmake:801 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:125 (include)

CMake Error: File /home/fra/phd2/tmp/external_libs_deflate/indi-2.0.3/libs/indibase/indiproperty.h does not exist.
CMake Error at thirdparty/thirdparty.cmake:801 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:125 (include)

CMake Error: File /home/fra/phd2/tmp/external_libs_deflate/indi-2.0.3/libs/indibase/indistandardproperty.h does not exist.
CMake Error at thirdparty/thirdparty.cmake:801 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:125 (include)

CMake Error: File /home/fra/phd2/tmp/external_libs_deflate/indi-2.0.3/libs/indibase/hidapi.h does not exist.
CMake Error at thirdparty/thirdparty.cmake:801 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:125 (include)

-- 'xgettext' program found at '/usr/bin/xgettext'
-- 'msgfmt' program found at '/usr/bin/msgfmt'
-- 'msgmerge' program found at '/usr/bin/msgmerge'
-- [DOC] Creating HTML target for locale en_EN
-- [DOC] Creating translation target for locale ar_LY
-- [DOC] Creating translation target for locale ca_ES
-- [DOC] Creating translation target for locale cs_CZ
-- [DOC] Creating translation target for locale de_DE
-- [DOC] Creating translation target for locale es_ES
-- [DOC] Creating HTML target for locale fr_FR
-- [DOC] Creating translation target for locale fr_FR
-- [DOC] Creating translation target for locale gl_ES
-- [DOC] Creating translation target for locale it_IT
-- [DOC] Creating HTML target for locale ja_JP
-- [DOC] Creating translation target for locale ja_JP
-- [DOC] Creating translation target for locale ko_KR
-- [DOC] Creating translation target for locale nb_NO
-- [DOC] Creating translation target for locale pl_PL
-- [DOC] Creating translation target for locale pt_BR
-- [DOC] Creating translation target for locale ro_RO
-- [DOC] Creating HTML target for locale ru_RU
-- [DOC] Creating translation target for locale ru_RU
-- [DOC] Creating translation target for locale uk_UA
-- [DOC] Creating translation target for locale zh_CN
-- [DOC] Creating HTML target for locale zh_TW
-- [DOC] Creating translation target for locale zh_TW
-- Configuring incomplete, errors occurred!

**Comment by agalasso** [comment]
fixed by #1093
