### ISSUE TITLE
Add ErrorCode description to EventMonitoring Wiki for GuideStep

### ISSUE THREAD

**Issue by isbeorn** [OpenPHDGuiding/phd2#1096]
Hi,

in the [GuideStep Section](https://github.com/OpenPHDGuiding/phd2/wiki/EventMonitoring#guidestep) of the Wiki there is a mention of ErrorCodes.
When looking at the Log Analysis on the PhD2 homepage, there are details which error code indicates which state: https://openphdguiding.org/man-dev/Trouble_shooting.htm#Log_analysis

It would be great to add these codes to the Wiki, too.

Thanks!

**Comment by bwdev01** [comment]
Good idea, I just updated it.  FWIW, the Wiki can be updated by anyone, it doesn't require developer credentials to do that.  Currently, the updated Wiki entry is more complete than what's in the Help doc so I will need to update the Help as well.  Thanks for the suggestion.

**Comment by isbeorn** [comment]
Thank you!
