### ISSUE TITLE
v2.6.12 Camera tab messed up in advanced settings

### ISSUE THREAD

**Issue by samhaa** [OpenPHDGuiding/phd2#1125]
v2.6.12 Camera tab messed up in advanced settings when camera has been connected.

![image](https://github.com/OpenPHDGuiding/phd2/assets/61279587/200b3b22-1b4c-405c-ac81-163716c41697)

**Comment by agalasso** [comment]
@samhaa thanks for letting us know about the issue.
Could you please provide more information:
 - what os and version are you using (Windows? Linux? If Windows, what version -- Windows 10, Windows 11, something else?)
 - What camera are you using?
 - What are the exact steps that you do in PHD2 to get the problem to show up?  For example: open, phd2, click the connect equipment button, than what?

Could you please provide a link to your PHD2 logs -- the log file upload instructions are here: https://openphdguiding.org/getting-help/

**Comment by bwdev01** [comment]
Also, you should be sure you are running the latest version of your camera drivers.  There have been many changes to the vendor-supplied SDK's during the life of 2.6.11.
