### ISSUE TITLE
Add the OGMA SDK to PHD2

### ISSUE THREAD

**Issue by OGMAvision** [OpenPHDGuiding/phd2#1178]
The OGMA brand has cameras that can be used for guiding.

The OGMA SDK is based on the Touptek SDK that is already integrated into PHD2.

The latest version of the OGMA SDK is located at https://github.com/OGMAvision/OGMAcamSDK

**Comment by agalasso** [comment]
OGMA cameras are supported in v2.6.13dev3 and later
