### ISSUE TITLE
locals_update.sh seems to be broken in the recent master.

### ISSUE THREAD

**Issue by Eyeke2** [OpenPHDGuiding/phd2#1229]
Maybe I miss something, but the script stopped working recently, possibly after relocation all source files to 'src' folder.

**Comment by Eyeke2** [comment]
@agalasso Suggested fix

diff --git a/cmake_modules/PHD2BuildDoc.cmake b/cmake_modules/PHD2BuildDoc.cmake
index 2af3c603..83424d14 100644
--- a/cmake_modules/PHD2BuildDoc.cmake
+++ b/cmake_modules/PHD2BuildDoc.cmake
@@ -330,7 +330,7 @@ function(generate_single_doc_targets)
               -E make_directory
               "${current_translation_output_folder}"
           COMMAND
-            ${XGETTEXT} *.cpp *.h -C
+            ${XGETTEXT} src/*.cpp src/*.h -C
               --from-code=CP1252
               --keyword="_"
               --keyword="wxPLURAL:1,2"

**Comment by agalasso** [comment]
@Eyeke2 thanks for tracking that down!
