### ISSUE TITLE
v2.6.13 macOS Sonoma+ does not open in Sonoma 14.5

### ISSUE THREAD

**Issue by Gary700** [OpenPHDGuiding/phd2#1242]
Problem is in title. The message is “PHD2.app” cannot be opened because the developer cannot be verified. Is there a solution? 

iMac Pro 2017 (Intel)

**Comment by agalasso** [comment]
https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unknown-developer-mh40616/mac
