### ISSUE TITLE
Enhancement Request:  Use PHD2 to help with SCT mirror shift

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenPHDGuiding/phd2#245]
```
What steps will reproduce the problem?
1. Buy an inexpensive SCT
2. Capture images at long focal length and long exposure times
3.

First of all, I'd like to express my thanks and appreciation for your work. 
I've just started using PHD2 and it looks to be a winner and I have not 
encountered any serious issues with the product.


Please provide any additional information below.

I've included a brief discussion of my request in the attached file.  TIA for 
your consideration of this request.

Regards,

jmh

```

Original issue reported on code.google.com by `John.Hoo...@gmail.com` on 12 Jan 2014 at 7:10

Attachments:
* [Request for Enhancement for PHD2 – Mirror Shift correction using PHD2.pdf](https://storage.googleapis.com/google-code-attachments/open-phd-guiding/issue-245/comment-0/Request for Enhancement for PHD2 – Mirror Shift correction using PHD2.pdf)

**Comment by agalasso** [comment]
We implemented infrastructure for this in PHD2. An application, FlexTerminator, was written to use the infrastructure to correct for differential flexure, and the results were reported in this thread,
https://groups.google.com/d/topic/open-phd-guiding/sO9bbibD2A4/discussion
