### ISSUE TITLE
Enable INDI support on OSX

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenPHDGuiding/phd2#348]
```
We should be able to support INDI on OSX

```

Original issue reported on code.google.com by `andy.gal...@gmail.com` on 19 Oct 2014 at 5:49

**Comment by d33psky** [comment]
related forum thread https://groups.google.com/forum/#!searchin/open-phd-guiding/INDI|sort:relevance/open-phd-guiding/7giSjSUT3pc/knwZC58th9AJ
