### ISSUE TITLE
Request to support QHY 5-II Mono camera on OSX

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenPHDGuiding/phd2#402]
```
see this thread:

https://groups.yahoo.com/neo/groups/stark-labs-astronomy-software/conversations/
topics/38335

camera reported to work on osx with oacapture:

http://www.openastroproject.org/tag/oacapture/

```

Original issue reported on code.google.com by `andy.gal...@gmail.com` on 20 Feb 2015 at 12:16

**Comment by goodwink** [comment]
oaCapture supports this camera in its current version.

**Comment by agalasso** [comment]
this issue is obsolete. qhy camera support has been available in PHD2 for macOS for some time now
