### ISSUE TITLE
request to be able to turn on cooling for cooled cameras

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenPHDGuiding/phd2#419]
```
a few users are using cooled CCD cameras for guiding and have requested the 
ability to be able to turn on the cooler in phd2
```

Original issue reported on code.google.com by `andy.gal...@gmail.com` on 9 Apr 2015 at 9:28

**Comment by bretm151** [comment]
I was thinking about this today, and it seems like it would be easy for ASCOM cameras to check if there is a cooler and if so, enable it at turn it way down (i.e. not provide a UI for the cooler, just enable it).  This would at least have the cooler on for ASCOM guide cameras that have them. It seems like a better default than off, and it would be easy to code.  Does this seem like a good idea?

**Comment by agalasso** [comment]
With my imaging camera if the relative humidity is high I have to carefully manage how fast the camera cools down otherwise I can get condensation.  So there is at least one case where just automatically turning it on could cause a problem.

**Comment by bwdev01** [comment]
Seems like it might be better to just bite the bullet and do a camera
properties UI for ASCOM cameras.  Looking at the ASCOM camera driver spec,
it doesn't look like there are too many properties to worry about for PHD2's
purposes:  binning, gain, fast readout, temp set-point, cooler on/off.  And
the ASCOM interface is pretty good about having "can" properties and ranges
on the other stuff.  Maybe it wouldn't be that hard to do a camera
properties dialog that supports all these things.  
 
To echo Andy's point, any conversation about camera cooling invariably
drifts into questions about a "warm-up" period, something people seem to
have strong opinions about.  So maybe it's not an area we can afford to
shortcut. 
 
Just my 2-cents.
Bruce
 
  _____

**Comment by agalasso** [comment]
apparently at least one camera driver already turns on cooling, and it's hard-coded to +10C

https://groups.google.com/d/msg/open-phd-guiding/O-3u-hVKm_k/Ca2MkamBfIcJ

**Comment by agalasso** [comment]
I just received another request to add this feature, in this case for an ASI 178MM camera.

**Comment by rwg0** [comment]
I have both cooled and uncooled ZWO cameras and would be happy to add the implementation for that camera type. From the sound of things though the design of cooled camera support - particularly where it goes in the UI still needs to be sorted out before writing any code :)

**Comment by agalasso** [comment]
Thanks Robin. I'll do the UI and the ASCOM camera case.  Bruce and I agreed that we would start with just settings for cooler on/off and setpoint temperature. The stats window will display on/off, setpoint, power, and current temperature. We'll omit doing any  warmup/cooldown code for now.

**Comment by bwdev01** [comment]
This sounds like a good solution.  I think we get people confused when the
device properties differ depending on whether they use an ASCOM or native
interface.
 
Bruce
 
  _____

**Comment by agalasso** [comment]
I added the infrastructure for cooled cameras in commit d9998ce2ab5bac4dceca7236c58645f4b61e6bc9

This should be straightforward to extend for ZWO and Atik cooled cameras or any others that are needed.

Caveat: the camera cooler status will be polled periodically in the main (UI) thread, potentially concurrently with the worker thread making image capture-related calls to the driver. Depending on whether or not the driver can handle concurrent access from separate threads there may need to be locking added to prevent concurrent access.

**Comment by rwg0** [comment]
ZWO cooled camera support added in commit 5aff2ff38c74cd231b5328a4216b9c3027aa4557

Very easy to add, thanks!. Tested with ASI1600MM-Cool

**Comment by agalasso** [comment]
this has been implemented now for ASCOM and ZWO.  if we need to implement it for other specific cameras we can add new tickets for each camera
