### ISSUE TITLE
Calibration sanity check should detect no-movement in east or south

### ISSUE THREAD

**Issue by bwdev01** [OpenPHDGuiding/phd2#443]
Even though the east/south moves have no bearing on the rate and angle calculations, we should flag situations where the star basically hasn't moved at all.  We have at least one incident in the field where this was a problem.

**Comment by d33psky** [comment]
I've had 'star did not move enough' messages -> can we close this ticket ?

**Comment by bwdev01** [comment]
No, that is something entirely different.  Please leave the ticket open.
 
  _____

**Comment by bwdev01** [comment]
Implemented via commit 0c75aab
