### ISSUE TITLE
Dec guiding exposure averaging seperate from RA

### ISSUE THREAD

**Issue by bhitzen** [OpenPHDGuiding/phd2#445]
Hi, 
As the declination drift in a well polar aligned mount is very small, I think having a seperate (from RA) averaging function which averages the star position in declination over several exposures and THEN (not after every single exposuser with any lowpass xx function) only corrects the DEC once would be very beneficial. This gets rid of most seeing-related star center measurement uncertainty in DEC and avoids unnecessary DEC correction commands which can have issues with backlash. 

Example: 1s exposure, dec-average 10

I suppose this could be done quite simply by only adding a counter to the generall guiding loop and averaging the DEC error and correcting it at the last (in this example 10th) loop. 
Together with a well chosen min-motion limit in DEC this then really should only correct if a real drift has taken place and averages out any seeing. Compared to RA the error is of completely different nature (very slow drift) so large averaging is clever, while in RA short correction intervals are needed. 

I think I could modify the code myself, but I'm quite unexperienced in compiling and setting up development environments. Besides I am not sure which branch to take as a basis. I'm now using PHD2 from the http://openphdguiding.org/  download (2.5.0 for windoof) I'll check the wiki, but if someone who is well experienced would like to have a look into this that would be great. 

Thanks for any kind of answer, regards Bernhard

**Comment by agalasso** [comment]
Hi Bernhard,

The Open PHD Guiding google group https://groups.google.com/forum/#!forum/open-phd-guiding is a great forum to bring up ideas like this.  We prefer to discuss ideas in the forum first, and reserve the issues repository for accepted bugs and open issues.

You can also get help with building PHD2 in the forum.

Andy
