### ISSUE TITLE
PHD2 on Windows should be able to connect to an INDI server

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#450]
INDI is currently only supported on Linux, with plans to support INDI on OSX (issue #348).  We should also add INDI support for the Windows version.  One use case would be for PHD2 running on Windows to connect to an INDI server running on Linux.

**Comment by d33psky** [comment]
The kstars port to windows was recently updated (http://www.indilib.org/jdownloads/kstars-x64-2.6.0-alpha.exe). It might have an INDI library that we can reuse here.

**Comment by agalasso** [comment]
Windows INDI support was added around the 2.6.3dev7 or dev8 time frame
