### ISSUE TITLE
PHD2 leaves ASCOM device driver running even after a disconnect

### ISSUE THREAD

**Issue by bwdev01** [OpenPHDGuiding/phd2#452]
On a disconnect from an ASCOM mount, we don't delete the m_scope instance.  This apparently leaves the COM resources in place, and the ASCOM driver continues to run.  Temporarily setting the Mount selection to 'None' fixes the problem because we then delete m_scope.  The OP says the same thing happens with an ASCOM camera driver.

**Comment by agalasso** [comment]
fixed in commit 8a7a879f46d18eab03623ff86b9925f944a0c654
