### ISSUE TITLE
PHD2 executable fails to run on some Windows XP SP3 installations

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#454]
Gives error:
CreateProcess failed; code 14001.

running depends.exe shows that SXUSB.dll introduced a dependency on MSVCR90.DLL (Visual C++ 2008 redistributable), however installing that dependency does not resolve the problem.

**Comment by bwdev01** [comment]
This isn't a PHD2 problem, per se, and we can't do anything about it on such an outdated OS.
