### ISSUE TITLE
Windows font scaling 125% hides OK/Cancel buttons on Slit Position dialog

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#469]
see this thread:
https://groups.yahoo.com/neo/groups/stark-labs-astronomy-software/conversations/topics/40683

**Comment by agalasso** [comment]
similar issue with the new equipment wizard:
https://groups.google.com/d/topic/open-phd-guiding/fLRyFb4x8uo/discussion

**Comment by bwdev01** [comment]
Problem affects multiple dialogs, basically those that use large, variable-length blocks of text in static text controls: drift alignment tool, new profile wizard, and guiding assistant.

**Comment by agalasso** [comment]
fixed by 719af6e2c39ce96f3c316f903191ff4bf8ff88a5
