### ISSUE TITLE
phd2 rejects bad-pixel map as invalid after binning is changed

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#471]
after changing binning and creating a new valid bad-pixel map, phd2 rejects the new map and declares that it is incompatible

https://groups.google.com/d/topic/open-phd-guiding/V8mvl3i4wRY/discussion

**Comment by agalasso** [comment]
I cannot reproduce this problem.

After the bad-pixel map is created for the new binning setting, there is an alert about the dark library being incompatible.  The dark library *is* incompatible, but maybe the alert is what is causing the confusion?

**Comment by bwdev01** [comment]
Can't reproduce, no further reports like this in over 4 months.
