### ISSUE TITLE
Norwegian translation

### ISSUE THREAD

**Issue by hholi** [OpenPHDGuiding/phd2#478]
Add norwegian translation.

**Comment by agalasso** [comment]
in case you hadn't seen it:
https://github.com/OpenPHDGuiding/phd2/wiki/TranslatingPHD2

**Comment by hholi** [comment]
Thanks, I saw that. When editing PHD settings it seems that it is only possible to select Default and English. I expected the drop-down to contain all languages in the locale folder. Is it something that I am missing?

**Comment by agalasso** [comment]
I believe you only see Default and English if you are running from the debugger.  You can put messages.mo and messages.po under the locales directory of a phd2 installation and you will see the new language when you run the installed phd2.

**Comment by d33psky** [comment]
Is this done ? Can this ticket be closed ?

**Comment by agalasso** [comment]
this is done!
