### ISSUE TITLE
New equipment wizard: fix detection of camera pixel size for cameras that cannot report pixel size

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#483]
some cameras, like WDM web cams, have no way to detect camera pixel size, yet the connect equipment wizard "Detect pixel size" button reports an incorrect pixel size (1 um) and does not report any error.

For cameras that cannot report pixel size it would be better to either disable the button, or hide the button, or show a message requesting the user to get the pixel size from the camera documentation.

**Comment by bwdev01** [comment]
Fixed, first release after 2.6.1dev5.  User-specified cam pixel size will be disabled if driver/device pixel size is available.  This is true for the profile wizard and also for the camera tab in the AD.
