### ISSUE TITLE
guiding assistant: do not abort process if backlash clearing fails

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#484]
see this thread:
https://groups.google.com/d/topic/open-phd-guiding/cp_eObv0X-I/discussion

from Bruce:
we should probably reconsider the behavior of the tool a bit – it may not be reasonable to end the whole process because of the backlash clearing failure.

**Comment by bwdev01** [comment]
Fixed. Now tolerates a poor RA calibration and also triggers recommendations to re-do the calibration if backlash clearing was dodgy or if the last calibration triggered an alert.
