### ISSUE TITLE
Guiding Assistant window does not fit on small screens

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#495]
from Fernando:

Hi, I've been using a Netbook Asus Eee PC 1005HA, to control my PHD2 and Nebulosity v3 and v4, for a while.
My monitor maximum resolution is 1024x600, I have 2 Gb RAM , and Windows 7.
Everything works fine with the PHD2 (2.5.0-dev9), except for one thing, when I open the "Guiding assistant" tool, the new window that opens don't show the 2 buttons (start-stop) and the (dec.backlash).
I don't know if I am missing something(I mean in Windows knowledge) or is somenthing else.
I really would like to use this tool, because all the others,"manual guide", "Comet tracking","Drift alignment",I tested each one, they work and appear entirely, only the GUiding assistant that don't.
Any thoughs, any help willbe welcome.

**Comment by bwdev01** [comment]
Resolved by user, just needed to reset screen resolution in Windows.  2.6 GA already has a landscape orientation with the recommendations positioned to the right of the measurements section.
