### ISSUE TITLE
Request to handle dec dither when dec guide mode is North or South

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#499]
When dec guide mode is uni-directional (North or South), we only allow dithering in RA. PHD2 could allow dec dithering for uni-directional guiding by detecting if the dither requires dec reversal. If reversal is required, PHD2 could temporarily changing guide mode Auto, intentionally over-shoot the lock position and then revert to uni-directional guiding.

**Comment by bwdev01** [comment]
Implemented in 915dc8e but without intentional over-correction
