### ISSUE TITLE
Review the code of all camera for GUI-call and make it work in the worker thread.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenPHDGuiding/phd2#50]
```
A device should not make GUI call except through proxy wrapper like the 
wxMessageBoxProxy.

To make it work in the worker thread, the functions HasNonGuiCapture and 
HasNonGuiMove must return true.

SBIG : OK
Simulator : OK
Starshoot Autoguider : OK
```

Original issue reported on code.google.com by `zesl...@gmail.com` on 17 May 2013 at 9:59

**Comment by agalasso** [comment]
all cameras currently use the worker thread.  In principle we can now remove the infrastructure for capture in the main thread.  The only motivation to keep it in would be if we anticipate needing to add a camera in the future that requires capture in the main thread.
