### ISSUE TITLE
request to determine "reverse dec output after meridian flip" setting automatically

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#504]
Chris Rowland suggested the idea of performing a pair of calibrations, one on each side of the meridian, to automatically determine the  "reverse dec output after meridian flip" setting.
perhaps use a wizard type interface to prompt the user when to do the meridian flip.

**Comment by bwdev01** [comment]
Marginal utility, not that difficult a problem for users to figure out.

**Comment by bwdev01** [comment]
From Andy:

If we were to do it I was envisioning a button next to the setting itself that would run the wizard.  Maybe we would also integrate it into the new equipment wizard, perhaps a checkbox similar to "build dark library" that says "calibrate meridian flip settings" or something like that (only present when pointing state is available)

**Comment by agalasso** [comment]
Fixed by 68b5a6a15ad5f01598496b46261615abc26d680e
