### ISSUE TITLE
Can't capture video with LogiLink USB video grabber

### ISSUE THREAD

**Issue by gabrielex83** [OpenPHDGuiding/phd2#505]
Apparently this particular video grabber is using a vfw driver and I can't find any newer driver that is WDM.
When trying to use this video capture device with PHD2 Guiding 2.6.1 I receive a "Failed to start video capture" message, probably because there's no way to select a vfw driver from there.
It used to work in the old PHD Guiding since there was VFW support.
How can I solve this issue?

**Comment by agalasso** [comment]
we do not have any plans right now to fix this.
you can either use phd1, or else you'll need to find a webcam or video capture device with a WDM driver
