### ISSUE TITLE
enhancement: Polar Alignment via internet plate-solving of CP region

### ISSUE THREAD

**Issue by ThemosTsikas** [OpenPHDGuiding/phd2#508]
There is a python utility that will calculate Polar Alignment error from two images of the Celestial Pole (CP) region taken as the camera is rotated about the RA axis. Ideally, one would take a horizontal image and a non-horizontal one, submit them to the utility and get an estimate of the azimuth and elevation components of the Polar Alignment error. It can use the nova.astrometry.net server or a local astrometry.net installation for plate-solving. Works in Southern or Northern Hemisphere.

https://github.com/ThemosTsikas/PhotoPolarAlign

It has been discusssed here 

https://stargazerslounge.com/topic/229902-looking-for-beta-testers-of-new-polar-alignment-utility/

Feel free to reuse any parts of the code to give PHD users access to this functionality.

**Comment by bwdev01** [comment]
Installation and support issues are too big for general use.
