### ISSUE TITLE
when restoring window position, phd2 should not allow windows to be placed off screen

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#518]
in case the screen size changes when switching monitors or switching from two monitors to one.

**Comment by bwdev01** [comment]
I think this issue really only applies to the main PHD2 frame.  If the main window is forced to be visible on whatever display is available, a 'restore window positions' will re-dock any other windows.

**Comment by agalasso** [comment]
I think we can just use wxSystemSettings::GetMetric wxSYS_SCREEN_X wxSYS_SCREEN_Y
to make sure the main window is visible

**Comment by agalasso** [comment]
fixed by commit 03d45432cf9416e801fb6515f1148039f81c7343
