### ISSUE TITLE
simulator stops guiding in dec ?

### ISSUE THREAD

**Issue by d33psky** [OpenPHDGuiding/phd2#519]
Simulator run, seem guiding stops in dec after a while. 

![20160320-phd2 6 1dev6-simulator-stopped-dec-guiding](https://cloud.githubusercontent.com/assets/2692514/13907535/b9eb0142-eef0-11e5-8867-29a002d131c8.jpg)

OS : Linux.

**Comment by agalasso** [comment]
could you attach the debug log?

**Comment by d33psky** [comment]
[PHD2_DebugLog_2016-03-20_225820.txt](https://github.com/OpenPHDGuiding/phd2/files/183719/PHD2_DebugLog_2016-03-20_225820.txt)

**Comment by bwdev01** [comment]
You're doing this with a simulated AO!  What you're seeing is expected
behavior when the AO has reached the limit of its travel and the mount needs
to be bumped.  The Dec corrections from the AO stop until the mount bump
returns the guide star back into a region where the AO can resume.  Since
you don't have a mount connection, bumping is not going to work. 
 
Bruce
 
  _____

**Comment by d33psky** [comment]
Yeah, the mount simulator seems gone. I can only select INDI,none,on-AO,on-Camera . I selected one of the on- options and got this result. Do we need a new ticket for the mount-simulator on Linux ?

**Comment by agalasso** [comment]
actually, we never had a mount simulator per se.  To use the internal phd2 simulators you would use:

Camera = Simulator
Mount = On-camera
AO = AO Simulator    or None

**Comment by bwdev01** [comment]
If you really want to see what's going on, you should use the AO graph when
you're using the AO simulator - that and connect to the "On camera" mount as
Andy said.
 
Bruce
 
  _____

**Comment by d33psky** [comment]
With mount = on-Camera the simulator works well \o/
With mount = on-AO the 'connect' button greys-out. This must have been the setup I intended to test.

I find it confusing that Camera can be set to Simulator while Mount cannot. Especially when an AO is added. To me 'mount = on-camera' means ST-4, and both my camera and my AO have ST-4 that can be connected to the mount.
In Real Life I want to connect with Mount set to an INDI mount interface, not ST-4 at all.

**Comment by agalasso** [comment]
I agree it is confusing.
Probably not worth changing at this point unless people feel really strongly about it. We do have a section dedicated to the simulators in the help file (openphdguiding.org/manual/?section=Basic_use.htm#Equipment_Connection)
