### ISSUE TITLE
INDI: detect side of pier

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#520]
can INDI report side of pier?

if so, then we should have phd2 use the pier side information in the same we we do for ASCOM.

**Comment by d33psky** [comment]
Created a feature request ticket for INDI at [https://sourceforge.net/p/indi/bugs/72/](https://sourceforge.net/p/indi/bugs/72/)

**Comment by pchev** [comment]
I remark that INDI Eqmod driver implement a PIERSIDE property.
I just commit an update for scope_INDI.cpp to return SideOfPier accordingly.
This need some testing because I am not sure if the returned value use the same rules as ASCOM.

**Comment by pchev** [comment]
Tested yesterday with indi_eqmod and HEQ5.
I set a 1 degree polar alignment error to make dec correction evident, calibrating with pointing east, then guiding pointing east and west after mount flip. Everything work as expected.
