### ISSUE TITLE
phd2 should ask for confirmation before calibrating at high declination

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#536]
phd2 should ask for confirmation before calibrating at high declination.
the confirmation message should include a "don't ask again" option

**Comment by agalasso** [comment]
suggestion from Bruce: associate the alert with the button click, not just the start of calibration so that it is only displayed for users starting calibration manually, not as part of an automated system

**Comment by bwdev01** [comment]
IDone, a5468c7
