### ISSUE TITLE
Rebuilding bad-pixel map master dark frame does not update stats in display

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#546]
open Refine Bad-pixel Map window
select Rebuild Master Dark Frame
click Generate

after master dark frame is built, the grid containing the details about the master dark are unchanged.  Not sure whether this is just a display issue, or whether the prior dark is being used. Either way it needs to be fixed.

**Comment by bwdev01** [comment]
Display problem, correct master dark (new one) was being used.  Fixed e24efd4.
