### ISSUE TITLE
guiding assistant text improvement

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#550]
consider clarifying that mount selection refers to mount connection (perhaps on-ao or on-camera), not necessarily the mount type

https://groups.google.com/d/topic/open-phd-guiding/YQP6qaJBnVE/discussion

**Comment by bwdev01** [comment]
I think this is an issue for the gear dialog and maybe the new-profile-wizard rather than the Guiding Assistant.  Might be able to handle it simply by supplying the missing tooltips for 'Camera' and 'Mount'.

**Comment by bwdev01** [comment]
Done.  Tooltip changes made to Gear dialog and new-profile-wizard.  GA was not affected.
