### ISSUE TITLE
Lots of missing buttons in "Guiding Assistant" for small screen netbooks

### ISSUE THREAD

**Issue by cytan299** [OpenPHDGuiding/phd2#561]
Hi guys,
   I use a netbook with a small screen to control my mount. Everything works _except_ Guiding Assistant because the Start, Stop buttons are missing. See picture that was attached to this bug report (phd2_missing_buttons.jpg)

Is it possible to have code to check for screen size, so that the buttons can appear on the side rather than at the bottom, or push all the tables closer to the top of the panel.

Thanks.

cytan

![phd2_missing_buttons](https://cloud.githubusercontent.com/assets/13826223/19413537/926c93fc-92f5-11e6-991c-b29f599c78c0.jpg)

**Comment by bwdev01** [comment]
This is problematic, and there are some minimum screen-size requirements for
PHD2.  Perhaps you could try this: http://www.gimespace.com/gms.html
 
And let us know if it works for you.
 
Thanks,
 
Bruce
 
  _____

**Comment by cytan299** [comment]
Hi Bruce,   Great suggestion! I just installed gimespace on my netbook and after fiddling with it and specifying that the guide assistant panel has to be 650 pixels high, now I can see the missing buttons.
cytan

**Comment by bwdev01** [comment]
Thanks for trying it and reporting back, Cytan.  This could be a useful
option for others. 
 
Bruce
 
  _____

**Comment by bwdev01** [comment]
Hi Cytan.  We're going to take a look at the Guiding Assistant layout and
try to restructure it a bit.  Can you tell me what your screen resolution is
- X pixels wide by Y pixels high?
 
Thanks,
Bruce
 
  _____

**Comment by cytan299** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Hi Bruce,
  It's 1024x600
  I can test it out once you have a fix.
  Thanks for a great piece of software.
Cytan


Sent from Yahoo Mail for iPad


On Sunday, October 16, 2016, 11:19 AM, bwdev01 <notifications@github.com> wrote:

Hi Cytan. We're going to take a look at the Guiding Assistant layout and
try to restructure it a bit. Can you tell me what your screen resolution is
- X pixels wide by Y pixels high?
 
Thanks,
Bruce
 
 _____

**Comment by bwdev01** [comment]
GA dialog layout revised to be approx 780w x 500h depending on # recommendations made.  Tested by OP.
