### ISSUE TITLE
allow 2-axis dither when dec guide mode is uni-directional

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#574]
Provide an option to switch Dec Guide Mode to Auto for dither; restore uni-directional dec guide mode after dither has settled.  This would only apply when the dither is initiated through the event server API, not through the PHD1 socket API since in the latter case PHD2 does not know when the imaging app has decided that the dither has settled.

**Comment by bwdev01** [comment]
Implemented with 915dc8e
