### ISSUE TITLE
Help file updates since Nov 2016

### ISSUE THREAD

**Issue by bwdev01** [OpenPHDGuiding/phd2#577]
1. Revise gear dialog image and text to explain choosing among multiple cameras of same type and use of ASCOM properties button
2. Changes to Dec dithering
3. Star-cross test
4. Consolidate the calibration-related issues, including declination backlash, into the trouble-shooting section.  Both the calibration section and the tools section should simply reference trouble-shooting.

**Comment by agalasso** [comment]
> Revise gear dialog image

you might want to hold off on grabbing the image since the choice button graphic is going to change (#576)

**Comment by bwdev01** [comment]
Done.
