### ISSUE TITLE
Build broken on linux armv7

### ISSUE THREAD

**Issue by domokos** [OpenPHDGuiding/phd2#600]
d38384b4ab89d0ce05e5f32212c95e9fed3f0cfd and 467b7ba907b58c5815ac2df4fb165aa021a1dca7 break build on linux armv7. 
Builds fine after reverting them.

Here's what I'm getting:

[ 42%] Linking CXX executable phd2
CMakeFiles/phd2.dir/cam_qhy.cpp.o: In function Camera_QHY::~Camera_QHY()': cam_qhy.cpp:(.text+0x64): undefined reference toReleaseQHYCCDResource'
CMakeFiles/phd2.dir/cam_qhy.cpp.o: In function Camera_QHY::Disconnect()': cam_qhy.cpp:(.text+0xa0): undefined reference toCancelQHYCCDExposingAndReadout'
cam_qhy.cpp:(.text+0xa8): undefined reference to CloseQHYCCD' CMakeFiles/phd2.dir/cam_qhy.cpp.o: In functionCamera_QHY::ST4PulseGuideScope(int, int)':
cam_qhy.cpp:(.text+0x114): undefined reference to ControlQHYCCDGuide' CMakeFiles/phd2.dir/cam_qhy.cpp.o: In functionCamera_QHY::~Camera_QHY()':
cam_qhy.cpp:(.text+0x190): undefined reference to ReleaseQHYCCDResource' CMakeFiles/phd2.dir/cam_qhy.cpp.o: In functionCamera_QHY::Capture(int, usImage&, int, wxRect const&)':
cam_qhy.cpp:(.text+0x5a8): undefined reference to SetQHYCCDBinMode' cam_qhy.cpp:(.text+0x5c8): undefined reference toCancelQHYCCDExposingAndReadout'
cam_qhy.cpp:(.text+0x770): undefined reference to SetQHYCCDResolution' cam_qhy.cpp:(.text+0x7c0): undefined reference toSetQHYCCDParam'
cam_qhy.cpp:(.text+0x9cc): undefined reference to SetQHYCCDParam' cam_qhy.cpp:(.text+0x9e4): undefined reference toExpQHYCCDSingleFrame'
cam_qhy.cpp:(.text+0xbbc): undefined reference to GetQHYCCDSingleFrame' cam_qhy.cpp:(.text+0x1770): undefined reference toExpQHYCCDSingleFrame'
CMakeFiles/phd2.dir/cam_qhy.cpp.o: In function Camera_QHY::Connect(wxString const&)': cam_qhy.cpp:(.text+0x2790): undefined reference toScanQHYCCD'
cam_qhy.cpp:(.text+0x2818): undefined reference to GetQHYCCDId' cam_qhy.cpp:(.text+0x2820): undefined reference toOpenQHYCCD'
cam_qhy.cpp:(.text+0x2830): undefined reference to IsQHYCCDControlAvailable' cam_qhy.cpp:(.text+0x35c4): undefined reference toOpenQHYCCD'
cam_qhy.cpp:(.text+0x36c0): undefined reference to SetQHYCCDStreamMode' cam_qhy.cpp:(.text+0x36d4): undefined reference toCloseQHYCCD'
cam_qhy.cpp:(.text+0x391c): undefined reference to InitQHYCCDResource' cam_qhy.cpp:(.text+0x3fb8): undefined reference toInitQHYCCD'
cam_qhy.cpp:(.text+0x3fc8): undefined reference to CloseQHYCCD' cam_qhy.cpp:(.text+0x4234): undefined reference toGetQHYCCDParamMinMaxStep'
cam_qhy.cpp:(.text+0x4270): undefined reference to GetQHYCCDChipInfo' cam_qhy.cpp:(.text+0x4280): undefined reference toCloseQHYCCD'
cam_qhy.cpp:(.text+0x4410): undefined reference to CloseQHYCCD' cam_qhy.cpp:(.text+0x4714): undefined reference toIsQHYCCDControlAvailable'
cam_qhy.cpp:(.text+0x47f8): undefined reference to IsQHYCCDControlAvailable' cam_qhy.cpp:(.text+0x4970): undefined reference toSetQHYCCDBinMode'
cam_qhy.cpp:(.text+0x49d4): undefined reference to GetQHYCCDMemLength' cam_qhy.cpp:(.text+0x4ae4): undefined reference toSetQHYCCDResolution'
cam_qhy.cpp:(.text+0x4af4): undefined reference to CloseQHYCCD' cam_qhy.cpp:(.text+0x4c30): undefined reference toCloseQHYCCD'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/phd2.dir/build.make:3072: phd2] Error 1
make[1]: *** [CMakeFiles/Makefile2:72: CMakeFiles/phd2.dir/all] Error 2
make: *** [Makefile:161: all] Error 2

**Comment by agalasso** [comment]
fixed by fe35d4365395558dbd0a088ed2cd8efde46e4a40
