### ISSUE TITLE
detect guide speed mismatch

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#633]
It's easy for a user to accept the default 0.5x guide speed in the new equipment wizard and overlook the Detect button.

PHD2 should automatically check the guide speed when connecting to an ASCOM or INDI mount and update the calibration step size and any other guide speed-dependent settings if there is a mismatch.

Could we even remove the Detect button?  Perhaps not -- there may be ASCOM drivers that do not provide the guide speed value, and for those we would still need the user to enter the guide speed manually. Perhaps the New equipment wiz should always try to attach to the mount? (and the camera to get the pixel size?)

**Comment by bwdev01** [comment]
Implemented as part of commit 45f2734
