### ISSUE TITLE
class wxSpinCtrl has no member named SetMax

### ISSUE THREAD

**Issue by justanenduser** [OpenPHDGuiding/phd2#657]
Your latest from GitHub gives the above error in profile_wizard.cpp line 676 column 30, line 679 column 30 and line 683 column 26.

/home/gary/Downloads/phd2-master/profile_wizard.cpp:676:30: error: ‘class wxSpinCtrl’ has no member named ‘SetMax’; did you mean ‘GetMax’?
             m_pBinningLevel->SetMax(cam->MaxBinning);
                              ^~~~~~
                              GetMax

/home/gary/Downloads/phd2-master/profile_wizard.cpp:679:30: error: ‘class wxSpinCtrl’ has no member named ‘SetMax’; did you mean ‘GetMax’?
             m_pBinningLevel->SetMax(4);         // We don't know, make it generous
                              ^~~~~~
                              GetMax

/home/gary/Downloads/phd2-master/profile_wizard.cpp:683:26: error: ‘class wxSpinCtrl’ has no member named ‘SetMax’; did you mean ‘GetMax’?
         m_pBinningLevel->SetMax(4);
                          ^~~~~~
                          GetMax

**Comment by agalasso** [comment]
fixed by 9229ad300203d368cd1fc9c96f2455e3fde09b6e
