### ISSUE TITLE
help file: more explanation of stop guiding when mount slews option

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#660]
From Eric:

> When would you NOT want to use "Stop guiding when mount slews"?
> I looked in the manual and it only says what the checkbox does, not when you'd want to use it or not.
> 
> I can't think of any reason you'd want to continue guiding when the mount slews, since the guide star will quickly be lost, but I assume there is a use for it?

discussion:
https://groups.google.com/d/topic/open-phd-guiding/hSNo1sKz_C0/discussion

**Comment by bwdev01** [comment]
Explanation added in d1415b2
