### ISSUE TITLE
Should debug logs contain guide log contents as well?

### ISSUE THREAD

**Issue by bretm151** [OpenPHDGuiding/phd2#671]
Watching the discussion go by on the Google group, it seems like support life might be easier if the debug log included the full contents of the guide log (maybe with a marker so you could you grep to create a guild log from a debug log?) so that users would only have to send 1 log file.

I don't feel strongly, but thought I would suggest it here -- feel free to close this if it seems like a bad idea.

**Comment by bwdev01** [comment]
We think the support clumsiness has been resolved via the 'Upload logs..." menu item.  Wholesale changes to either log format would break a bunch of private support tools.
