### ISSUE TITLE
Guiding Assistant min-motion may be too low when long guide exposures are used

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#672]
The GA min-motion recommendation seems to work best when 1-2s guide exposures are used for the GA run.  When longer exposures are used the high frequency motion appears to be under-estimated resulting in a min-motion recommendation that is too low.

**Comment by bwdev01** [comment]
Shouldn't be a problem now with the revised technique for estimating seeing based on Dec rms.  However, best results will still come from using the exposure time that will be used for actual guiding.
