### ISSUE TITLE
Some strings not translatable

### ISSUE THREAD

**Issue by lock042** [OpenPHDGuiding/phd2#677]
In the help menu, some strings are not translatable as seen in attachment.
![phd2](https://user-images.githubusercontent.com/16907662/36024364-d6a828e0-0d8f-11e8-81c5-07c2dff8df9f.png)

**Comment by agalasso** [comment]
ok, thanks, the translation templates have been updated 7beee7e70e32d19f766810edbfac76d866eb5127
