### ISSUE TITLE
phd2 crashing using INDI driver

### ISSUE THREAD

**Issue by glauria** [OpenPHDGuiding/phd2#692]
Hi,

I'm using phd2 with an INDI driver and it's been crashing a lot.  My setup is a Raspberri PI 3 which is the server running the indi drivers and I'm using phd2 through KStars/Ekos with my client machine running Windows 7.  The crash occurs randomly while I'm guiding.  I checked the INDI log file to see if there were any problems with the communication with my guide camera (Meade DSI Pro II mono) and there doesn't seem to be any issues.  i.e., like having a bad USB cable from the camera to the RPI3.  

Is there a log file that phd2 creates which might report the problem before it crashes?  The weird thing about this problem is that it started all of the sudden.  Up until recently, (only a week or so ago), phd2 was working just fine and now it's crashing.  Also, the time it crashes also seems to be random.  i.e., I'll start go guide and the crash happens either a minute or so or several minutes into guiding.  Any offer on where I might start to look for the problem would be greatly appreciated.

Clear skies,
-Gene

**Comment by agalasso** [comment]
Gene, there is info about phd2 log files in the phd2 help file (menu: Help > Contents > Logging) and on the phd2 web site: https://openphdguiding.org/getting-help/  

Let's track this issue in the PHD2 forum for now.  We prefer to use the github issue tracker for actionable bugs and feature requests.  We can open a new issue here in the issue tracker if necessary after we get more information.

**Comment by glauria** [comment]
Thanks Andy,

Sorry that it took a while for me to reply.  (Whole bunch of other stuff 
going on.)  Originally, I thought the problem might be with INDI/Ekos so 
I asked Jasem Mutlaq first, and he referred me to the PHD2 Github page.  
I'll post the issue on the PHD2 forum and upload the log file.  
Hopefully, the error will be able to be tracked from there and will be 
an easy fix.

Clear skies,
-Gene
