### ISSUE TITLE
Add warnings in new-profile wiz for simulator mis-use and on-camera choice for real hardware

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#697]
apparently not everyone reads the manual :roll_eyes: 

we should display an informational message with a "don't show this again" option if somebody connects a mount other than On-camera with the camera simulator selected.   Simulated guiding with the camera simulator is only possible when the mount selection is On-camera.

**Comment by bwdev01** [comment]
On the flip-side,  also generate some kind of notification discouraging use of "on-camera" for mount selection in normal (real hardware) profiles.

**Comment by bwdev01** [comment]
Fixed as part of commit 78ee9f0.  Mount choice in wizard is skipped if camera = simulator.
