### ISSUE TITLE
Building on Windows 10

### ISSUE THREAD

**Issue by funkysandman** [OpenPHDGuiding/phd2#700]
Hi, I followed the steps in the wiki to build the solution in Windows.  Everything builds and looks fine, but when I run the PHD2 project it doesn't ever produce the main window.  Am I missing something?
Here is the output log:
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\phd2.exe'. Symbols loaded.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntdll.dll'. Symbols loaded.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel32.dll'. Symbols loaded.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. Symbols loaded.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\apphelp.dll'. Symbols loaded.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shell32.dll'. Symbols loaded.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcrt.dll'. Symbols loaded.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cfgmgr32.dll'. Symbols loaded.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ucrtbase.dll'. Symbols loaded.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\SHCore.dll'. Symbols loaded.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rpcrt4.dll'. Symbols loaded.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sspicli.dll'. Symbols loaded.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cryptbase.dll'. Symbols loaded.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\bcryptprimitives.dll'. Symbols loaded.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sechost.dll'. Symbols loaded.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\combase.dll'. Cannot find or open the PDB file.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\windows.storage.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\advapi32.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shlwapi.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\gdi32.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\gdi32full.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcp_win.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\user32.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\win32u.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel.appcore.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\powrprof.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\profapi.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ole32.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\oleaut32.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\LIBCURL.DLL'. Module was built without symbols.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\setupapi.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.16299.431_none_5d750ac5a7e1c779\comctl32.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ws2_32.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wsock32.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\Wldap32.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\comdlg32.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\ShoestringGPUSB_DLL.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Unloaded 'C:\phd2-master\tmp\Debug\ShoestringGPUSB_DLL.dll'
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\ShoestringLXUSB_DLL.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Unloaded 'C:\phd2-master\tmp\Debug\ShoestringLXUSB_DLL.dll'
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\crypt32.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\ASICamera2.dll'. Module was built without symbols.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msasn1.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\altaircamsdk.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\qhyccd.dll'. Module was built without symbols.
'phd2.exe' (Win32): Unloaded 'C:\phd2-master\tmp\Debug\qhyccd.dll'
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\DICAMSDK.dll'. Module was built without symbols.
'phd2.exe' (Win32): Unloaded 'C:\phd2-master\tmp\Debug\DICAMSDK.dll'
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\FcApi.dll'. Module was built without symbols.
'phd2.exe' (Win32): Unloaded 'C:\phd2-master\tmp\Debug\FcApi.dll'
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\SXUSB.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Unloaded 'C:\phd2-master\tmp\Debug\SXUSB.dll'
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\CMOSDLL.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\inpout32.dll'. Module was built without symbols.
'phd2.exe' (Win32): Unloaded 'C:\phd2-master\tmp\Debug\CMOSDLL.dll'
'phd2.exe' (Win32): Unloaded 'C:\phd2-master\tmp\Debug\inpout32.dll'
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\opencv_highgui2410d.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\opencv_imgproc2410d.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcp120d.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Unloaded 'C:\phd2-master\tmp\Debug\opencv_imgproc2410d.dll'
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\opencv_core2410d.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Unloaded 'C:\phd2-master\tmp\Debug\opencv_core2410d.dll'
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winspool.drv'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcr120d.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_508dca76bcbcfe81\msvcr90.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\AltairCam.dll'. Module was built without symbols.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvfw32.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\avifil32.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\avicap32.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\IPHLPAPI.DLL'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\bcrypt.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Program Files (x86)\Visual Leak Detector\bin\Win32\vld_x86.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Unloaded 'C:\Program Files (x86)\Visual Leak Detector\bin\Win32\vld_x86.dll'
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winmm.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msacm32.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winmm.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\winmm.dll'
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winmmbase.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winmmbase.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winmmbase.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\winmmbase.dll'
'phd2.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\winmmbase.dll'
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winmmbase.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\winmmbase.dll'
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\ShoestringGPUSB_DLL.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\ShoestringLXUSB_DLL.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\qhyccd.dll'. Module was built without symbols.
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\DICAMSDK.dll'. Module was built without symbols.
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\SXUSB.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\FcApi.dll'. Module was built without symbols.
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\CMOSDLL.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\inpout32.dll'. Module was built without symbols.
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\opencv_imgproc2410d.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\opencv_core2410d.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\opencv_core2410d.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Program Files (x86)\Visual Leak Detector\bin\Win32\vld_x86.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\hid.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\hid.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winusb.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\hid.dll'
'phd2.exe' (Win32): Loaded 'C:\phd2-master\tmp\Debug\tbb.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcr120.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_508dca76bcbcfe81\msvcp90.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\msvcr120.dll'
'phd2.exe' (Win32): Unloaded 'C:\phd2-master\tmp\Debug\opencv_core2410d.dll'
'phd2.exe' (Win32): Loaded 'C:\Program Files (x86)\Visual Leak Detector\bin\Win32\dbghelp.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Unloaded 'C:\Program Files (x86)\Visual Leak Detector\bin\Win32\dbghelp.dll'
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcr120.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Program Files (x86)\Visual Leak Detector\bin\Win32\dbghelp.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\imm32.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winpcap.dll'. Module was built without symbols.
'phd2.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\winpcap.dll'
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winpcap.dll'. Module was built without symbols.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\version.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\uxtheme.dll'. User canceled automatic symbol loading.
First-chance exception at 0x76F53F12 (KernelBase.dll) in phd2.exe: 0x000006A6: The binding handle is invalid.
Visual Leak Detector read settings from: C:\Program Files (x86)\Visual Leak Detector\vld.ini
Visual Leak Detector Version 2.5.1 installed.
The thread 0x2058 has exited with code 0 (0x0).
00:12:36.868 07.208 22128 PHD2 version 2.6.5dev1 begins execution with:
00:12:37.170 00.302 22128    Windows 8 (build 9200), 64-bit edition
00:12:37.389 00.219 22128    wxWidgets 3.0.4
00:12:37.596 00.207 22128    cfitsio 3.37
00:12:37.717 00.121 22128 CoInitializeEx returns 1
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\secur32.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mswsock.dll'. User canceled automatic symbol loading.
00:12:38.068 00.351 22128 Using Locale Dir C:\phd2-master\tmp\Debug\locale exists=1
00:12:38.225 00.157 22128 GetInt("/wxLanguage", 0) returns 0
00:13:00.743 22.518 22128 GetString("/frame/LogDir", "") returns ""
00:13:03.667 02.924 22128 GetInt("/currentProfile", 0) returns 2
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msctf.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dwmapi.dll'. User canceled automatic symbol loading.
00:13:04.411 00.744 22128 reset dither spiral
00:13:05.016 00.605 22128 StartWorkerThread(00000000) begins
00:13:05.324 00.308 22128 WorkerThread constructor called
00:13:05.449 00.125 17176 WorkerThread::Entry() begins
00:13:05.584 00.135 22128 StartWorkerThread(00A12FE8) ends
00:13:05.732 00.148 17176 worker thread CoInitializeEx returns 0
00:13:05.871 00.139 22128 StartWorkerThread(00000000) begins
00:13:06.006 00.135 22128 WorkerThread constructor called
00:13:06.131 00.125 9288 WorkerThread::Entry() begins
00:13:06.236 00.105 22128 StartWorkerThread(00A149B0) ends
00:13:06.372 00.136 9288 worker thread CoInitializeEx returns 0
00:13:06.584 00.212 22128 GetBoolean("/ServerMode", 1) returns 1
00:13:20.641 14.057 22128 GetInt("/profile/2/NoiseReductionMethod", 0) returns 0
00:13:20.893 00.252 22128 GetDouble("/profile/2/DitherScaleFactor", 1.000000) returns 1.000000
00:13:21.133 00.240 22128 GetBoolean("/profile/2/DitherRaOnly", 0) returns 0
00:13:21.348 00.215 22128 GetInt("/profile/2/DitherMode", 0) returns 0
00:13:21.471 00.123 22128 set dither mode 0
00:13:21.664 00.193 22128 GetInt("/profile/2/frame/timeLapse", 0) returns 0
00:13:22.043 00.379 22128 GetInt("/profile/2/AutoLoadCalibration", -1) returns -1
00:13:22.284 00.241 22128 GetInt("/profile/2/frame/focalLength", 0) returns 0
00:13:22.703 00.419 22128 GetInt("/profile/2/auto_exp/exposure_min", 1000) returns 1000
00:13:22.894 00.191 22128 GetInt("/profile/2/auto_exp/exposure_max", 5000) returns 5000
00:13:23.066 00.172 22128 GetDouble("/profile/2/auto_exp/target_snr", 6.000000) returns 6.000000
00:13:23.187 00.121 22128 AutoExp: config min = 1000 max = 5000 snr = 6.00
00:13:23.503 00.316 22128 AutoExp: reset exp to 5000
00:13:23.736 00.233 22128 GetInt("/profile/2/CustomExposureDuration", 30000) returns 30000
00:13:23.971 00.235 22128 GetInt("/profile/2/ExposureDurationMs", 1000) returns 1000
00:13:24.117 00.146 22128 OnExposureDurationSelected: duration = 1000
00:13:24.352 00.235 22128 GetInt("/profile/2/Gamma", 100) returns 172
00:13:24.789 00.437 22128 GetBoolean("/profile/2/ImageLogger/LoggingEnabled", 0) returns 0
00:13:25.157 00.368 22128 GetBoolean("/profile/2/ImageLogger/LogFramesOverThreshRel", 0) returns 0
00:13:25.357 00.200 22128 GetBoolean("/profile/2/ImageLogger/LogFramesOverThreshPx", 0) returns 0
00:13:25.591 00.234 22128 GetBoolean("/profile/2/ImageLogger/LogFramesDropped", 0) returns 0
00:13:25.761 00.170 22128 GetBoolean("/profile/2/ImageLogger/LogAutoSelectFrames", 0) returns 0
00:13:26.001 00.240 22128 GetDouble("/profile/2/ImageLogger/ErrorThreshRel", 4.000000) returns 4.000000
00:13:26.178 00.177 22128 GetDouble("/profile/2/ImageLogger/ErrorThreshPx", 4.000000) returns 4.000000
00:13:26.316 00.138 22128 ImgLogger: Settings LogEnabled=0 Log Rel=0, 0.00 Log Px=0, 0.00 LogFrameDrop=0 LogAutoSel=0 NextN=0
00:13:26.475 00.159 22128 GetBoolean("/profile/2/indi/VerboseLogging", 0) returns 0
00:13:27.805 01.330 22128 GetInt("/profile/2/overlay/slit/center.x", 376) returns 376
00:13:27.979 00.174 22128 GetInt("/profile/2/overlay/slit/center.y", 290) returns 290
00:13:28.153 00.174 22128 GetInt("/profile/2/overlay/slit/width", 8) returns 8
00:13:28.319 00.166 22128 GetInt("/profile/2/overlay/slit/height", 100) returns 100
00:13:28.504 00.185 22128 GetInt("/profile/2/overlay/slit/angle", 0) returns 0
00:13:28.813 00.309 22128 Changing from state 0 to 0
00:13:29.041 00.228 22128 GetBoolean("/profile/2/guider/FastRecenter", 1) returns 1
00:13:29.485 00.444 22128 GetBoolean("/profile/2/guider/ScaleImage", 1) returns 1
00:13:29.901 00.416 22128 GetDouble("/profile/2/guider/StarMinHFD", 0.000000) returns 0.000000
00:13:30.070 00.169 22128 Setting StarMinHFD = 0.00
00:13:30.328 00.258 22128 GetDouble("/profile/2/guider/onestar/MassChangeThreshold", 0.500000) returns 0.500000
00:13:30.600 00.272 22128 GetBoolean("/profile/2/guider/onestar/MassChangeThresholdEnabled", 1) returns 1
00:13:30.822 00.222 22128 GetInt("/profile/2/guider/onestar/SearchRegion", 15) returns 15
00:13:31.038 00.216 22128 GetBoolean("/StickyLockPosition", 0) returns 0
00:13:31.359 00.321 22128 GetString("/geometry", "") returns "0;1417;925;392;15"
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\clbcatq.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\DataExchange.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\d3d11.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dcomp.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dxgi.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\twinapi.appcore.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rmclient.dll'. User canceled automatic symbol loading.
'phd2.exe' (Win32): Loaded 'C:\Windows\SysWOW64\WindowsCodecs.dll'. User canceled automatic symbol loading.
00:13:33.661 02.302 22128 GetInt("/graph/ScopeOrCameraUnits", 0) returns 0
00:13:33.860 00.199 22128 GetString("/graph/RAColor", "") returns "#6464FF"
00:13:34.122 00.262 22128 GetString("/graph/DecColor", "") returns "#FF0000"
00:13:34.332 00.210 22128 GetInt("/graph/minLength", 50) returns 50
00:13:34.743 00.411 22128 GetInt("/graph/maxLength", 400) returns 400
00:13:35.122 00.379 22128 GetInt("/graph/minHeight", 1) returns 1
00:13:35.311 00.189 22128 GetInt("/graph/maxHeight", 16) returns 16
00:13:35.581 00.270 22128 GetInt("/graph/length", 100) returns 100
00:13:35.784 00.203 22128 GetInt("/graph/height", 4) returns 4
00:13:36.030 00.246 22128 GetInt("graph/HeightUnits", 1) returns 1
00:13:36.246 00.216 22128 GetBoolean("/graph/showCorrections", 1) returns 1
00:13:36.488 00.242 22128 GetBoolean("/graph/showStarMass", 0) returns 0
00:13:36.706 00.218 22128 GetBoolean("/graph/showStarSNR", 0) returns 0
00:13:48.205 11.499 22128 GetInt("/graph_stepguider/length", 1) returns 1
00:13:50.367 02.162 22128 GetInt("/target/length", 100) returns 100
00:13:50.540 00.173 22128 GetDouble("/target/zoom", 1.000000) returns 1.000000
00:13:53.090 02.550 22128 GetBoolean("/profile/2/target/refCircleEnabled", 0) returns 0
00:13:53.260 00.170 22128 GetDouble("/profile/2/target/refCircleRadius", 2.000000) returns 2.000000
The thread 0x3770 has exited with code 0 (0x0).
The thread 0x4ff4 has exited with code 0 (0x0).
The thread 0x3a58 has exited with code 0 (0x0).
The thread 0x431c has exited with code 0 (0x0).

**Comment by funkysandman** [comment]
If I leave the machine alone for about 5 minutes, the main screen finally shows up.  What is slowing everything down?  Is there something in the project I can disable to speed things up?

**Comment by agalasso** [comment]
I think the slowness is probably die to VLD.  Try disabling VLD in vld.ini

https://github.com/KindDragon/vld/wiki/Configuration-Options

**Comment by funkysandman** [comment]
Thanks!  That was the culprit
