### ISSUE TITLE
calibration settings UI cleanup

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#703]
- The calibration step size calculator window is too tall for small screens. It needs to be rearranged to be wider and less tall.
- let's move the calibration distance setting into the calstep dialog and change the button from "Calculate..." to "Advanced...";  rationale: as long as the New equipment profile wizard is being used, there is little or no need to manually change the step size or calibration distance.  We would like to move the controls out of the main settings area to an out-of-the-way "advanced" settings dialog.
- The advanced calibration settings window should give the user a way to reset the calibration distance and/or calibration step size back to default values (computed from image scale, guide speed, etc.).

**Comment by bwdev01** [comment]
Fixed with commits 2022ca7, 705a861
