### ISSUE TITLE
INDI: allow aux mount connection to mount that does not have GUIDER interface

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#715]
PHD2 is excluding any INDI telescope devices that doe not have the GUIDER interface.  It should be accepting devices with the TELESCOPE interface for use as an Aux mount even if they do not have the GUIDER interface.

**Comment by DerPit** [comment]
Is this supposed to work properly?
I do have a synscan mount, handled by INDI.  I can indeed select an INDI Aux mount, and in the config tab the connection to INDI is visible (localhost+port), and I am offered the synscan as mount.  But trying to connect ends in a timeout :( (EKOS is also connected to the mount)
(2.6.5dev5, INDI 1.7.4)

**Comment by agalasso** [comment]
@DerPit  could you either open a new issue or post in the phd2 forum. I don't think your problem has anything to do with this issue related to aux mount.  you should just select INDI for the mount , I don't think you need aux mount at all

**Comment by DerPit** [comment]
indi_synscan doesn't support pulseguide, that's why I need the ST4 port (plus AUX mount).  It isn't offered as option for normal mount.  That's why I thought it would fit here.  Will open another ticket.  Thanks.
