### ISSUE TITLE
Documentation: Overview about available "Polar alignment" methods in PHD2:

### ISSUE THREAD

**Issue by deix** [OpenPHDGuiding/phd2#734]
Hi,

I have seen, that there have been available some new methods to obtain polar alignment in recent PHD2 releases. Would it not be beneficial for the user (especially the older ones, that not yet have used the new methods) to have kind of "overview" about possible choices: advantages, disadvantages, requirements connected with selecting specific methods. I am thinking about the table like this could contribute to understanding the method and helping choosing the best one: (please note, that the values used are "dummys" and need to be updated)

![polar alignment](https://user-images.githubusercontent.com/8902727/48844583-92e49300-ed9a-11e8-8e74-6c9c465751e3.png)

Source: [Polar alignment.txt](https://github.com/OpenPHDGuiding/phd2/files/2604340/Polar.alignment.txt)

Best regards
Michal

**Comment by agalasso** [comment]
great idea, thanks for the suggestion

**Comment by bwdev01** [comment]
Fixed with commit 6f126e0
