### ISSUE TITLE
serialport_posix.cpp: 2 * bad if ?

### ISSUE THREAD

**Issue by dcb314** [OpenPHDGuiding/phd2#735]
1.

phd2-2.6.5/serialport_posix.cpp:163]: (style) Suspicious condition (assignment + comparison); Clarify expression with parentheses.

Source code is

    if ((ioctl_ret = ioctl(m_fd, TIOCMGET, &argp) < 0)) {

Maybe better code
    if ((ioctl_ret = ioctl(m_fd, TIOCMGET, &argp)) < 0) {

2.

phd2-2.6.5/serialport_posix.cpp:172]: (style) Suspicious condition (assignment + comparison); Clarify expression with parentheses.

Duplicate.

**Comment by agalasso** [comment]
thanks for pointing out the problem
