### ISSUE TITLE
[Enhancement] Spectroscopy: support two-lobed stars

### ISSUE THREAD

**Issue by kehak** [OpenPHDGuiding/phd2#739]
Doing high-resolution spectroscopy happens to be tedious or impossible with PHD2, as it currently lacks the ability to do slit guiding (guiding on a two-lobed star).

At high focal lengths (eg, C14 f/D10), the FOV is too narrow to guide on a different star, and trying to guide the target star on the slit edge will cause various "mass changed" or "star lost" errors as the flux varies as the star moves in and out of the slit.

Professional or semi-professional software are designed to handle this but unfortunately don't support INDI, so having PHD2 support slit guiding is paramount for amateur spectroscopists, especially at high resolution.

This issue has been brought before but apparently stalled:
https://code.google.com/archive/p/open-phd-guiding/issues/249

Let me know if I can assist you testing the feature, should you implement it.

**Comment by agalasso** [comment]
duplicate #249 
(I have added a reference to this issue from #249 to capture your comments)
