### ISSUE TITLE
new profile wiz: change default dec guide algo for mounts with absolute encoders 

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#766]
for mounts with absolute encoders and virtually no dec backlash, the default dec guide algorithm should probably be hysteresis, not resist switch.

**Comment by agalasso** [comment]
the Guiding Assistant should also recommend using Hys for Dec if the backlash measurement yields a very small backlash, like less than 50 ms or so.

**Comment by bwdev01** [comment]
After more simulation, the default Dec algo for these conditions is now Lowpass2.  Implemented in commit 5d08314
