### ISSUE TITLE
API: RPC call ignored when too close

### ISSUE THREAD

**Issue by pludov** [OpenPHDGuiding/phd2#777]
My client app ([Mobindi](https://github.com/pludov/mobindi)) uses the event monitoring api and does some polling for various stuff, issuing: 
* get_calibration_data,
* get_current_equipment,
...

Requests to the EventMonitoring port are sent randomly on the same socket, and sometime concurrently (meaning two starts in a row).

Once i a while, a request is never answered. I nailed it down to drain_input in handle_cli_input (event_server.cpp). Basically, once the first line of the read buffer has been processed, the leftover is just trashed, even if it contains other requests...

**Comment by agalasso** [comment]
Currently you can avoid the problem if you make your make your RPC calls one at a time.  That is how all the existing clients are working.

   send request 1
   read response 1
   send request 2
   read response 2

I will look into adding support for overlapping requests.
