### ISSUE TITLE
Query re status bar info

### ISSUE THREAD

**Issue by TheDiscoDuck** [OpenPHDGuiding/phd2#786]
The status bar during guiding is showing the corrections in ms and px. At least I assumed they were the corrections. But (version 2.6.6) they seem to be the offsets (at least for the px value).

Line 967-968 of aui_controls.cpp:
m_GuideIndicators->UpdateState(info.directionRA, info.directionDec, fabs(info.mountOffset.X),
        info.durationRA, fabs(info.mountOffset.Y), info.durationDec);

Is it meant to show the correction instead, e.g. guideDistanceRA instead of mountOffset.X anmd similarly for Dec?

**Comment by agalasso** [comment]
this is working as designed and we would like to leave it as is.... showing the mount correction in milliseconds and the guide star offset in pixels.
The guide distance and guide duration are directly proportional, so showing both of those would be a bit redundant.
Guide distance and duration and and mount offset are all available in the guide log.
