### ISSUE TITLE
About dialog html window cannot display some unicode characters

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#796]
inserting a unicode character greater then \u00ff like \u0142 into the wxHtmlWindow text causes all the text in the the window to disappear

**Comment by PawelPleskaczynski** [comment]
Try to use numeric character reference of a symbol, eg. ł is `&#322;` and ń is `&#324;`

**Comment by agalasso** [comment]
that worked, thanks!
