### ISSUE TITLE
new profile wiz: detect EQASCOM and direct user to update EQMOD settings

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#808]
New profile wiz should detect incorrect (default) EQASCOM settings and direct user to the EQASCOM settings for PHD2 wiki page.
Maybe also provide a check & alert outside the profile wiz as well (with a don't show again option).
We can detect EQASCOM by name, and use the reported guide speed as an indication of whether the user needs to be advised.

BTW, I have emailed Chris, the EQMOD maintainer, last year and again today requesting that the EQMOD default guide speed be changed, but have not received any reply.

**Comment by bwdev01** [comment]
Implemented via 67f4c86
