### ISSUE TITLE
phd2 crash when connecting a second camera of the same type when the first camera does not support subframes but the second one does

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#814]
repro requires two camera of the same type (e.g. 2 touptek cameras), with one that supports subframes and the other does not

1. open the connect equipment dialog,
2. use the forked-arrows button to select the non-subframe-capable camera (e.g. G3CMOS02300KPA)
3. connect and then close the connect equip window
4. open the connect equipment dialog again,
5. hit disconnect
6. use the forked-arrows button to select the subframe-capable camera (e.g. G3CMOS02000KPA)
7. connect and then close the connect equip window
phd2 crashes at
```
CameraConfigDialogCtrlSet::LoadValues
989             m_pUseSubframes->SetValue(m_pCamera->UseSubframes);
```
as m_pUseSubframes is uninitialized.

**Comment by bwdev01** [comment]
This happened only if the two cameras have different pixel sizes in addition to different capabilities.  Fixed via commit 151bd8c
