### ISSUE TITLE
PHD2 cannot run on macOS Catalina (64 bit requirement)

### ISSUE THREAD

**Issue by archcorsair** [OpenPHDGuiding/phd2#819]
**Description:**
I am unable to launch PHD2 on MacOS Catalina.

**Reproduction Steps:**
1. Download latest PHD2 release
2. Attempt to open
3. Get following error:
![image](https://user-images.githubusercontent.com/1036921/70277935-24396400-1768-11ea-866c-44d1888de4cf.png)
Learn More button takes you to [this link](https://support.apple.com/en-us/HT208436)

**System Details:**
- MacOS Catalina 10.15.1 (19B2106)
- PHD2 2.6.6
- PHD2 2.6.6dev2 (Also does not work)

**Comment by agalasso** [comment]
there has been lots of activity in the forum related to macOS 64-bit development... please follow the forum for the latest info.
The current best build for macOS Catalina is here: https://groups.google.com/d/msg/open-phd-guiding/pM4lhfo7UC8/jXVjyE7UAQAJ
