### ISSUE TITLE
guide speed mismatch check far less sensitive to dec speed change than ra

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#824]
in mount.ccp
if (fabs(1.0 - currRASpeed / calDetails.raGuideSpeed) > 0.05 || fabs(1.0 - currDecSpeed / calDetails.decGuideSpeed) > 0.5)

ra speed change of 5% triggers the alert, but dec speed must change by 50% to trigger the alert.

**Comment by bwdev01** [comment]
Fixed with commit 985fa48
