### ISSUE TITLE
UI Scaling on high DPI screens

### ISSUE THREAD

**Issue by RononDex** [OpenPHDGuiding/phd2#832]
I am having issues with PHD2 scaling with high DPI screens:
![image](https://user-images.githubusercontent.com/2249071/72604622-89fa3d80-391b-11ea-8614-4ba01e3601da.png)
This is a screenshot from my surface book (which runs Arch Linux and I use to control my astro setup).

The checkbox is incredibly tiny compared to the text (screen is 14.3", 3000x2000)

**Comment by agalasso** [comment]
The size of the check-boxes is out of the control of PHD2 and is determined by Arch.
On my phd2 development machine with 4K monitor I have my display scaling setting at the default (Auto). (System Settings > Display > Settings > User interface scaling).
From your screenshot fragment it looks like you are perhaps scaling fonts? (on my system: System Settings > Font Selection > Text scaling factor).   I've got it at 1.4 on my system.

**Comment by RononDex** [comment]
The size of checkboxes being controlled by Arch doesnt make any sense to me...
Arch is a distro, it has 0 influence what so ever on DPI scaling
DPI scaling comes from X11, GDK or QT

**Comment by agalasso** [comment]
> DPI scaling comes from X11, GDK or QT
yes, exactly correct  (it does not come from PHD2, and PHD2 has no control over it)

**Comment by RononDex** [comment]
But why do other applications just work fine then?

**Comment by agalasso** [comment]
I have no idea

**Comment by RononDex** [comment]
Hmm strange, I'll have to check some config files then, thanks for the help though :)

**Comment by agalasso** [comment]
ok, please let us know what you find so we can help other users who encounter this problem.

I'm going to close this ticket since there is nothing actionable at this time for phd2.
