### ISSUE TITLE
documentation: add a statement about how phd does not require an internet connection

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#840]
PHD2 does not require an internet connection

When PHD2 starts up and the the "Check for updates" option is enabled, PHD2 will connect to openphdguiding.org to check for a newer version of PHD2.   If there is no internet connection, nothing happens (PHD2 will check again next time it starts up with the Check for updates option enabled.)

The Upload log files option on the Help menu does require an internet connection to upload the log files to the server.

We should also add data privacy statement, but we can put that on the web site (rather than in the help file)

**Comment by bwdev01** [comment]
The 'software updates' section already covers the internet connection question, but I will add to the short help sentence that's shown in the Advanced Settings help.
