### ISSUE TITLE
How to install PHD2 in Raspbian,Raspbian system has no GUI

### ISSUE THREAD

**Issue by supermyc** [OpenPHDGuiding/phd2#852]
I want to install PHD2 in Raspbian， but Raspbian system has no GUI，thanks！！

**Comment by agalasso** [comment]
@supermyc for submitting questions related to phd2, please post in the phd2 forum: https://openphdguiding.org/getting-help/
we prefer to use the github issue tracker for tracking our open bugs and feature requests
