### ISSUE TITLE
Drift Align window uses hardcoded background color

### ISSUE THREAD

**Issue by rkaczorek** [OpenPHDGuiding/phd2#855]
https://github.com/OpenPHDGuiding/phd2/blob/61ad9da0654d062f7ab954639d5fffe4d78a5fc8/drift_tool.cpp#L141

This results in unreadable text if dark themes are used e.g. in rasbian buster (openbox). See example screenshot.

![Screenshot from 2020-04-16 23-12-39](https://user-images.githubusercontent.com/17554493/79507444-03e3b500-8038-11ea-8fb3-728dfeb5f62b.png)

**Comment by pchev** [comment]
I remove the fixed color in drifttool, polardrift and staticpa.

For drifttool I also change the arrow xpm background to transparent, this must be tested on Windows because I no more have a working compilation environment.

**Comment by rkaczorek** [comment]
Confirmed fix
