### ISSUE TITLE
Multi-Star Guiding - feedback on documentation

### ISSUE THREAD

**Issue by deix** [OpenPHDGuiding/phd2#899]
After reading the "docs" for the latest development build, I have the following fedback (suggestions for making it more specific):

1. "...some of the secondary stars may be rejected because they are too dim or have drifted outside the field of view..." - does the  algorithm also reject stars when they became saturated ? 

2. "...The multi-star algorithm uses the secondary stars to refine the centroid position and reduce its volatilty, so there is essentially no way for it to degrade guiding performance...." - what happens, when the primary star get either too dimm / drifts from field of view or became saturated ? Does the algoritm picks the "best" secondary star and re-use it as the primary ?

3. "...12 stars in the field of view that have adequate SNR.  No more than 9 of these will be used at any one time..." - can You add the visualisation of "not active" stars that have been picked by auto-select:
- usual rectangle around the primary star
- green circles around the "active" secondary stars (up to 9 stars)
- red circles around the "not active" secondary stars (up to 12 stars)

 4. "...to replace secondary stars that are lost or rejected for some reason..." - You could list here the the criteria used in the algorithm, like e.g.:
- below SNR treshold
- too close to edge / drifted outside the field of view
- drifted inside frame (e.g. comet, geostationary satelite, etc...)
- saturated 
- etc...

**Comment by bwdev01** [comment]
Hi Michael, thanks for the comments.  The manual generally focuses on
information that is needed to *use* a feature.  What you're talking about
here is mostly implementation-level detail and is subject to change at any
time. And none of it has any effect on your ability to use the feature.  For
this level of detail, the source code is the best reference, one of the
benefits of open-source software.   I've provided answers to your specific
questions based on the current state of the dev3 release.
 
  _____

**Comment by deix** [comment]
Thank You for the answers to your specific questions Bruce - let's close this post since there are no actions to be taken on it.
/ Michal
