### ISSUE TITLE
PHD Dither App download links on the website do not work in Google Chrome

### ISSUE THREAD

**Issue by akozhanov** [OpenPHDGuiding/phd2#901]
Hi PHD2 team, 
Not sure if anyone else has had this issue or whether it is the right place here to post this issue: I tried to download the PHD Dither App from the PHD2 website but the link (http://openphdguiding.org/PHD_Dither_Release1b.zip) did not work for me in Google Chrome. 
Google Chrome Developer Tools reported this reason: 
Mixed Content: The site at 'https://openphdguiding.org/' was loaded over a secure connection, but the file at 'https://openphdguiding.org/PHD_Dither_Release1b.zip' was redirected through an insecure connection. This file should be served over HTTPS. This download has been blocked.
Entering the URL manually and replacing http with https in the URL (i.e. https://openphdguiding.org/PHD_Dither_Release1b.zip) did help and I could download the app. Perhaps the link on the website needs to be changed to, I assume other people using Google Chrome are having the same problem.

Many thanks for your effort, PHD2 is an excellent tool!

Andriy.

**Comment by agalasso** [comment]
Thanks for pointing out the problem @akozhanov .  The website has been updated and the links should be working now.
