### ISSUE TITLE
SVBONY cameras support not working on PHD2 2.6.9 dev4

### ISSUE THREAD

**Issue by marekbohdan** [OpenPHDGuiding/phd2#913]
Hi!
I have a SVBONY SV205 camera, PHD2 2.6.9 dev4, Windows 10 Pro 64 bit. I choose "Svbony Camera" and I get "No cameras found". Camera is connected via USB 2.0 and 3.0 (cables and ports). Camera works fine as "Windows WDM-style webcam camera".

**Comment by bwdev01** [comment]
We would much prefer that you deal with this in our active user forum: https://groups.google.com/g/open-phd-guiding  .  This is very unlikely to be a problem in the PHD2 code.  After making sure you have installed the correct SVBONY camera driver, you will need to provide us with a PHD2 debug log.
