### ISSUE TITLE
add option to slew scope to calibration location

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#959]
Message from Chuck in the google group forum:

I have a suggestion for PHD2. As a newbie, I didn't understand where in the sky I was supposed to point the guide scope for calibration. The recommendation was to point it at the meridian and equator. And I thought, "hmm, I wonder where that is." I eventually figured it out, but I also stumbled across the Drift Align tool, which will automatically move to the correct location, just by hitting the "Slew" button. No thinking needed on my part, excellent! So that's what I always use now. But this isn't obvious to newbies.

So now, I repeatedly read on the support forums about people struggling the same way I did. Much time is wasted back and forth between users and the experts as they get the concept of pointing at meridian/equator understood. But, since the code already exists in the Drift Align routine, wouldn't it be relatively easy, and extremely user friendly, if the same tool could be implemented in the calibration routine?

Here's my idea. When PHD2 starts a calibration, it checks to see where the scope is pointing. If it isn't in the ideal part of the sky, a pop-up displays that tells the user that the scope is not pointed in the correct direction, and just like the current Drift Align pop-up, it tells the user the current pointing, the slew to coordinates, as well as a button to initiate the mount slew.

What do you think?

-chuck-

**Comment by bwdev01** [comment]
Implemented as part of the Calibration Assistant in 2.6.11dev5 release.
