### ISSUE TITLE
Rotator Failing to Connect via Server Control (Voyager)

### ISSUE THREAD

**Issue by CCrunner84** [OpenPHDGuiding/phd2#982]
Hi All,

When connecting & disconnecting devices via Voyager, my Factor Rotator always fails to connect after a Disconnect & Reconnect of all devices.  Connecting it manually seems to resolve the issue after the error is displayed, going into equipment and pressing connect, or doing another 'Connect' via Voyager seems to fix the issue as well.

14:48:36.044 01.921 8060 gear_dialog: OnButtonConnectRotator
14:48:36.045 00.001 8060 Status Line: Connecting to Rotator ...
14:48:36.048 00.003 8060 Connecting to rotator [PegasusAstro Falcon (ASCOM)]
14:48:36.073 00.025 8060 invoke: [80020009] Exception occurred.
14:48:36.076 00.003 8060 Status Line: Rotator Connected
14:48:36.080 00.004 8060 Connected Rotator:PegasusAstro Falcon (ASCOM)

**Comment by bwdev01** [comment]
You should move this to the OpenPHD2 google forum where you will need to then upload your guide and debug log files.  Operational support problems like this should be posted on the forum, the "issues" on GitHub are intended for identified programming problems and new-feature requests.
