### ISSUE TITLE
Latency in download pictures with  touptek gcmos1200kb

### ISSUE THREAD

**Issue by CarlosMagni** [OpenPHDGuiding/phd2#989]
I got a latency about 0.5 second to download pictures taken from de ToupTek cam into phd2. That's a constant latency. From 0.01s to infinity there is still around 0.5 second lost in data transfert. This is not the camera or the cable because in fireCapture i can reach 30 fps

**Comment by bwdev01** [comment]
Please post your question on the OpenPHD2 Google support forum.  What you're seeing is entirely normal because PHD2 uses the guide camera in single-exposure mode, it doesn't stream the video like FireCapture.  

Bruce
