### ISSUE TITLE
phd2 failing to start on Raspberry Pi OS 64bit Buster

### ISSUE THREAD

**Issue by phomer60** [OpenPHDGuiding/phd2#999]
After building latest version from repository on Raspberry Pi OS 64bit Buster, the programs fails to start.

Not sure if there are any logs I can check.

Paul

**Comment by agalasso** [comment]
@phomer60 what do you see if you run PHD2 from a terminal window?

**Comment by phomer60** [comment]
/usr/bin/phd2.bin: error while loading shared libraries: libSVBCameraSDK.so: cannot open shared object file: No such file or directory

**Comment by phomer60** [comment]
Dependencies checked as per instructions on [https://github.com/OpenPHDGuiding/phd2/wiki/BuildingPHD2OnLinux](url) and everything is installed.

**Comment by phomer60** [comment]
Since INDI now appears to run under Bullseye 64bit I am no longer going to worry about this.

**Comment by jruizluque** [comment]
Take a look at this PR [https://github.com/OpenPHDGuiding/phd2/pull/1011](https://github.com/OpenPHDGuiding/phd2/pull/1011)

**Comment by agalasso** [comment]
I believe this was resolved so closing it now.
